-- MySQL Script generated by MySQL Workbench
-- Sat Apr 18 22:56:07 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoria` ;

CREATE TABLE IF NOT EXISTS `categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único de la categoría. Auto incremental',
  `nombre` VARCHAR(60) NOT NULL COMMENT 'Nombre de la categoría. Ej: Sub-15, Sub-17',
  `edad_minima` TINYINT UNSIGNED NOT NULL COMMENT 'Edad mínima permitida en años',
  `edad_maxima` TINYINT UNSIGNED NOT NULL COMMENT 'Edad máxima permitida en años',
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
COMMENT = 'Almacena las categorías deportivas de la academia de fútbol \n(Ej: Sub-15, Sub-17). Define los rangos de edad mínima y máxima \npermitidos para clasificar a los jugadores y organizar los \nentrenamientos por grupo etario.'
KEY_BLOCK_SIZE = 16;


-- -----------------------------------------------------
-- Table `lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lugar` ;

CREATE TABLE IF NOT EXISTS `lugar` (
  `id_lugar` INT NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria autoincremental. Identifica de forma única cada instalación deportiva registrada en el sistema',
  `nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre oficial o coloquial del lugar o cancha. Ej: Cancha Principal, Estadio El Bosque',
  `descripcion` TEXT NULL COMMENT 'Descripción libre del espacio físico. Incluye características como tipo de superficie, capacidad o condiciones del terreno',
  `direccion` VARCHAR(255) NOT NULL COMMENT 'Dirección física completa del lugar incluyendo calle, barrio y ciudad para facilitar la ubicación del entrenador',
  PRIMARY KEY (`id_lugar`))
ENGINE = InnoDB
COMMENT = 'Catálogo de instalaciones deportivas donde se llevan a cabo \nlas sesiones de entrenamiento. Permite al entrenador gestionar \ny consultar los espacios físicos disponibles, asociando cada \nsesión a un lugar específico para facilitar la planificación \ny organización logística de la academia.';


-- -----------------------------------------------------
-- Table `persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `persona` ;

CREATE TABLE IF NOT EXISTS `persona` (
  `identificacion` VARCHAR(15) NOT NULL COMMENT 'Clave primaria. Número de documento de identidad de la persona. Puede ser cédula de ciudadanía para mayores de edad o tarjeta de identidad para menores',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre o nombres de la persona tal como aparece en su documento de identidad',
  `apellido` VARCHAR(45) NOT NULL COMMENT 'Apellido o apellidos de la persona tal como aparece en su documento de identidad',
  PRIMARY KEY (`identificacion`))
ENGINE = InnoDB
COMMENT = 'Entidad padre de la jerarquía de generalización. Almacena los \natributos comunes a todas las personas registradas en el sistema: \nentrenadores, jugadores y acudientes. Implementa herencia por \ntabla por tipo (Table-per-Type). La identificación puede ser \ncédula de ciudadanía o tarjeta de identidad según la edad.';


-- -----------------------------------------------------
-- Table `entrenador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entrenador` ;

CREATE TABLE IF NOT EXISTS `entrenador` (
  `cedula_entrenador` VARCHAR(15) NOT NULL COMMENT 'Clave primaria y foránea hacia PERSONA. Número de documento de identidad del entrenador',
  `email` VARCHAR(120) NOT NULL COMMENT 'Correo electrónico único del entrenador. Usado como credencial de acceso al sistema',
  `contrasena` VARCHAR(255) NOT NULL COMMENT 'Contraseña de acceso almacenada como hash bcrypt. Nunca se guarda en texto plano',
  `telefono` VARCHAR(20) NOT NULL COMMENT 'Número de contacto principal. Campo opcional ya que los jugadores menores de edad pueden no tener teléfono propio. En ese caso el contacto se gestiona a través del acudiente',
  PRIMARY KEY (`cedula_entrenador`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_entrenador_persona`
    FOREIGN KEY (`cedula_entrenador`)
    REFERENCES `persona` (`identificacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Especialización de PERSONA. Almacena los atributos exclusivos \ndel entrenador deportivo. Hereda identificacion, nombre, apellido de PERSONA. Es el único rol con acceso al sistema.';


-- -----------------------------------------------------
-- Table `jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jugador` ;

CREATE TABLE IF NOT EXISTS `jugador` (
  `identificacion_jugador` VARCHAR(15) NOT NULL COMMENT 'Clave primaria y foránea hacia PERSONA. Documento de identidad del jugador.',
  `fecha_nacimiento` DATE NOT NULL COMMENT 'Fecha de nacimiento del jugador en formato ISO YYYY-MM-DD. Permite verificar que el jugador cumple el rango de edad establecido por su categoría',
  `posicion` VARCHAR(20) NOT NULL COMMENT 'Posición habitual del jugador en el campo. Valores permitidos: Portero, Defensa, Mediocampista, Delantero',
  `id_categoria` INT NOT NULL COMMENT 'Clave foránea hacia CATEGORIA. Indica la categoría etaria a la que pertenece el jugador dentro de la academia',
  PRIMARY KEY (`identificacion_jugador`),
  INDEX `fk_jugador_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_jugador_persona`
    FOREIGN KEY (`identificacion_jugador`)
    REFERENCES `persona` (`identificacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_jugador_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `categoria` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Especialización de PERSONA. Almacena los atributos \nexclusivos del jugador deportivo. No tiene teléfono propio \ndado que puede ser menor de edad. El contacto se gestiona \na través de su acudiente.';


-- -----------------------------------------------------
-- Table `acudiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acudiente` ;

CREATE TABLE IF NOT EXISTS `acudiente` (
  `cedula_acudiente` VARCHAR(15) NOT NULL COMMENT 'Clave primaria y foránea hacia PERSONA. Cédula de ciudadanía del acudiente.',
  `telefono` VARCHAR(20) NOT NULL COMMENT 'Número de contacto principal del acudiente. Es el canal de comunicación con la academia cuando el jugador es menor de edad',
  `parentesco` VARCHAR(30) NOT NULL COMMENT 'Relación familiar o legal del acudiente con el jugador. Ej: Padre, Madre, Tío, Hermano, Tutor legal',
  `identificacion_jugador` VARCHAR(15) NOT NULL COMMENT 'Clave foránea hacia JUGADOR. Indica a qué jugador pertenece este acudiente. Relación uno a uno',
  PRIMARY KEY (`cedula_acudiente`),
  INDEX `fk_acudiente_jugador_idx` (`identificacion_jugador` ASC) VISIBLE,
  UNIQUE INDEX `identificacion_jugador_UNIQUE` (`identificacion_jugador` ASC) VISIBLE,
  CONSTRAINT `fk_acudiente_persona`
    FOREIGN KEY (`cedula_acudiente`)
    REFERENCES `persona` (`identificacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_acudiente_jugador`
    FOREIGN KEY (`identificacion_jugador`)
    REFERENCES `jugador` (`identificacion_jugador`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Especialización de PERSONA. Almacena el contacto responsable \nde cada jugador menor de edad registrado en la academia. \nGarantiza que siempre exista un adulto responsable vinculado \na cada jugador. Implementa la única relación 1:1 del modelo.';


-- -----------------------------------------------------
-- Table `entrenamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entrenamiento` ;

CREATE TABLE IF NOT EXISTS `entrenamiento` (
  `id_entrenamiento` INT NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria autoincremental. Identificador único de cada sesión de entrenamiento registrada en el sistema',
  `fecha` DATE NOT NULL COMMENT 'Fecha programada de la sesión en formato ISO YYYY-MM-DD',
  `hora_inicio` TIME NOT NULL COMMENT 'Hora de inicio de la sesión en formato HH:MM:SS',
  `hora_fin` TIME NOT NULL COMMENT 'Hora de finalización de la sesión en formato HH:MM:SS',
  `tipo` VARCHAR(45) NOT NULL COMMENT 'Clasificación de la sesión. Valores permitidos: Físico, Táctico, Técnico, Mixto',
  `estado` ENUM('programado', 'realizado', 'cancelado') NOT NULL COMMENT 'Estado actual de la sesión. Valores: programado, realizado, cancelado',
  `observacion` TEXT NULL COMMENT 'Notas libres del entrenador registradas al finalizar la sesión. Campo opcional',
  `id_lugar` INT NOT NULL COMMENT 'Clave foránea hacia LUGAR. Indica la instalación deportiva donde se realiza el entrenamiento',
  `id_categoria` INT NOT NULL COMMENT 'Clave foránea hacia CATEGORIA. Indica el grupo etario al que va dirigido el entrenamiento',
  `cedula_entrenador` VARCHAR(15) NOT NULL COMMENT 'Clave foránea hacia ENTRENADOR. Indica qué entrenador dirige la sesión',
  `id_plan_mongodb` VARCHAR(24) NULL COMMENT 'Identificador del documento en MongoDB que contiene el plan detallado de la sesión. ObjectId en formato hexadecimal de 24 caracteres',
  PRIMARY KEY (`id_entrenamiento`),
  INDEX `fk_entrenamiento_lugar_idx` (`id_lugar` ASC) VISIBLE,
  INDEX `fk_entrenamiento_categoria_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_entrenamiento_entrenador_idx` (`cedula_entrenador` ASC) VISIBLE,
  CONSTRAINT `fk_entrenamiento_lugar`
    FOREIGN KEY (`id_lugar`)
    REFERENCES `lugar` (`id_lugar`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entrenamiento_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `categoria` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entrenamiento_entrenador`
    FOREIGN KEY (`cedula_entrenador`)
    REFERENCES `entrenador` (`cedula_entrenador`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Entidad central del sistema. Registra cada sesión de entrenamiento \nprogramada o realizada por la academia. Actúa como puente entre \nla base de datos relacional MySQL y MongoDB a través del campo \nid_plan_mongodb, que referencia el plan detallado de la sesión \nalmacenado en formato documental.';


-- -----------------------------------------------------
-- Table `asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asistencia` ;

CREATE TABLE IF NOT EXISTS `asistencia` (
  `id_entrenamiento` INT NOT NULL COMMENT 'Clave primaria compuesta y foránea hacia ENTRENAMIENTO. Identifica la sesión a la que corresponde el registro de asistencia',
  `identificacion_jugador` VARCHAR(15) NOT NULL COMMENT 'Clave primaria compuesta y foránea hacia JUGADOR. Identifica el jugador cuya asistencia se está registrando',
  `estado_asistencia` ENUM('presente', 'ausente', 'justificado') NOT NULL COMMENT 'Estado de asistencia del jugador a la sesión. Valores: presente, ausente, justificado',
  `observacion` TEXT NULL COMMENT 'Motivo de ausencia o nota adicional sobre la asistencia del jugador. Campo opcional',
  PRIMARY KEY (`id_entrenamiento`, `identificacion_jugador`),
  INDEX `fk_asistencia_jugador_idx` (`identificacion_jugador` ASC) VISIBLE,
  CONSTRAINT `fk_asistencia_entrenamiento`
    FOREIGN KEY (`id_entrenamiento`)
    REFERENCES `entrenamiento` (`id_entrenamiento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_asistencia_jugador`
    FOREIGN KEY (`identificacion_jugador`)
    REFERENCES `jugador` (`identificacion_jugador`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Entidad asociativa que registra la asistencia de cada jugador \na cada sesión de entrenamiento. Implementa la relación N:M \nentre JUGADOR y ENTRENAMIENTO. Su clave primaria compuesta \ngarantiza que no se dupliquen registros de asistencia para \nel mismo jugador en la misma sesión.';

-- -----------------------------------------------------
-- Table `log entrenamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS log_entrenamiento (
    id_log           INT NOT NULL AUTO_INCREMENT,
    id_entrenamiento INT NOT NULL,
    estado_anterior  VARCHAR(20) NOT NULL,
    estado_nuevo     VARCHAR(20) NOT NULL,
    fecha_cambio     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_db       VARCHAR(50) NOT NULL,
    PRIMARY KEY (id_log)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='Tabla de auditoria para cambios de estado en entrenamientos.';
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
